# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\EQ\EQ_gui\mw.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1229, 947)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cw = QtWidgets.QWidget(self.centralwidget)
        self.cw.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.cw.setMinimumSize(QtCore.QSize(750, 500))
        self.cw.setMaximumSize(QtCore.QSize(1000, 800))
        self.cw.setObjectName("cw")
        self.gridLayout = QtWidgets.QGridLayout(self.cw)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.cw)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 971, 511))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.toolBox = QtWidgets.QToolBox(self.tab_2)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 401, 451))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 401, 316))
        self.page.setObjectName("page")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 111, 21))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setGeometry(QtCore.QRect(0, 20, 391, 201))
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.IDLE_SELcomboBox = QtWidgets.QComboBox(self.widget)
        self.IDLE_SELcomboBox.setObjectName("IDLE_SELcomboBox")
        self.IDLE_SELcomboBox.addItem("")
        self.IDLE_SELcomboBox.addItem("")
        self.gridLayout_5.addWidget(self.IDLE_SELcomboBox, 1, 1, 1, 1)
        self.IDLE_AUTOcomboBox = QtWidgets.QComboBox(self.widget)
        self.IDLE_AUTOcomboBox.setObjectName("IDLE_AUTOcomboBox")
        self.IDLE_AUTOcomboBox.addItem("")
        self.IDLE_AUTOcomboBox.addItem("")
        self.gridLayout_5.addWidget(self.IDLE_AUTOcomboBox, 0, 1, 1, 1)
        self.RXDETcomboBox = QtWidgets.QComboBox(self.widget)
        self.RXDETcomboBox.setMinimumSize(QtCore.QSize(0, 50))
        self.RXDETcomboBox.setObjectName("RXDETcomboBox")
        self.RXDETcomboBox.addItem("")
        self.RXDETcomboBox.addItem("")
        self.RXDETcomboBox.addItem("")
        self.RXDETcomboBox.addItem("")
        self.gridLayout_5.addWidget(self.RXDETcomboBox, 2, 1, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 401, 316))
        self.page_2.setObjectName("page_2")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(0, 20, 77, 20))
        self.label_12.setObjectName("label_12")
        self.widget1 = QtWidgets.QWidget(self.page_2)
        self.widget1.setGeometry(QtCore.QRect(10, 70, 331, 81))
        self.widget1.setObjectName("widget1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_14 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.EQControlcomboBox = QtWidgets.QComboBox(self.widget1)
        self.EQControlcomboBox.setObjectName("EQControlcomboBox")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.EQControlcomboBox.addItem("")
        self.gridLayout_6.addWidget(self.EQControlcomboBox, 1, 0, 1, 3)
        self.label_15 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 0, 2, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.widget2 = QtWidgets.QWidget(self.page_3)
        self.widget2.setGeometry(QtCore.QRect(10, 10, 321, 141))
        self.widget2.setObjectName("widget2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_16 = QtWidgets.QLabel(self.widget2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 0, 0, 1, 1)
        self.SCPcomboBox = QtWidgets.QComboBox(self.widget2)
        self.SCPcomboBox.setObjectName("SCPcomboBox")
        self.SCPcomboBox.addItem("")
        self.SCPcomboBox.addItem("")
        self.gridLayout_7.addWidget(self.SCPcomboBox, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 1, 0, 1, 1)
        self.RATE_SELcomboBox = QtWidgets.QComboBox(self.widget2)
        self.RATE_SELcomboBox.setObjectName("RATE_SELcomboBox")
        self.RATE_SELcomboBox.addItem("")
        self.RATE_SELcomboBox.addItem("")
        self.gridLayout_7.addWidget(self.RATE_SELcomboBox, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 2, 0, 1, 1)
        self.VODCcomboBox = QtWidgets.QComboBox(self.widget2)
        self.VODCcomboBox.setObjectName("VODCcomboBox")
        self.VODCcomboBox.addItem("")
        self.VODCcomboBox.addItem("")
        self.VODCcomboBox.addItem("")
        self.VODCcomboBox.addItem("")
        self.VODCcomboBox.addItem("")
        self.VODCcomboBox.addItem("")
        self.VODCcomboBox.addItem("")
        self.VODCcomboBox.addItem("")
        self.gridLayout_7.addWidget(self.VODCcomboBox, 2, 1, 1, 1)
        self.toolBox.addItem(self.page_3, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.widget3 = QtWidgets.QWidget(self.page_5)
        self.widget3.setGeometry(QtCore.QRect(30, 20, 191, 31))
        self.widget3.setObjectName("widget3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_21 = QtWidgets.QLabel(self.widget3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 0, 0, 1, 1)
        self.DEMcomboBox = QtWidgets.QComboBox(self.widget3)
        self.DEMcomboBox.setObjectName("DEMcomboBox")
        self.DEMcomboBox.addItem("")
        self.DEMcomboBox.addItem("")
        self.DEMcomboBox.addItem("")
        self.DEMcomboBox.addItem("")
        self.DEMcomboBox.addItem("")
        self.DEMcomboBox.addItem("")
        self.DEMcomboBox.addItem("")
        self.DEMcomboBox.addItem("")
        self.gridLayout_8.addWidget(self.DEMcomboBox, 0, 1, 1, 1)
        self.toolBox.addItem(self.page_5, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.widget4 = QtWidgets.QWidget(self.page_4)
        self.widget4.setGeometry(QtCore.QRect(40, 70, 241, 71))
        self.widget4.setObjectName("widget4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_19 = QtWidgets.QLabel(self.widget4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 0, 0, 1, 1)
        self.IDLEthacomboBox = QtWidgets.QComboBox(self.widget4)
        self.IDLEthacomboBox.setObjectName("IDLEthacomboBox")
        self.IDLEthacomboBox.addItem("")
        self.IDLEthacomboBox.addItem("")
        self.IDLEthacomboBox.addItem("")
        self.IDLEthacomboBox.addItem("")
        self.gridLayout_9.addWidget(self.IDLEthacomboBox, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 1, 0, 1, 1)
        self.IDLEthdcomboBox = QtWidgets.QComboBox(self.widget4)
        self.IDLEthdcomboBox.setObjectName("IDLEthdcomboBox")
        self.IDLEthdcomboBox.addItem("")
        self.IDLEthdcomboBox.addItem("")
        self.IDLEthdcomboBox.addItem("")
        self.IDLEthdcomboBox.addItem("")
        self.gridLayout_9.addWidget(self.IDLEthdcomboBox, 1, 1, 1, 1)
        self.toolBox.addItem(self.page_4, "")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(580, 90, 311, 111))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.widget5 = QtWidgets.QWidget(self.groupBox_5)
        self.widget5.setGeometry(QtCore.QRect(20, 10, 141, 91))
        self.widget5.setObjectName("widget5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CH0checkBox = QtWidgets.QCheckBox(self.widget5)
        self.CH0checkBox.setObjectName("CH0checkBox")
        self.gridLayout_4.addWidget(self.CH0checkBox, 0, 0, 1, 1)
        self.CH1checkBox = QtWidgets.QCheckBox(self.widget5)
        self.CH1checkBox.setObjectName("CH1checkBox")
        self.gridLayout_4.addWidget(self.CH1checkBox, 1, 0, 1, 1)
        self.CH3checkBox = QtWidgets.QCheckBox(self.widget5)
        self.CH3checkBox.setObjectName("CH3checkBox")
        self.gridLayout_4.addWidget(self.CH3checkBox, 4, 0, 1, 1)
        self.CH5checkBox = QtWidgets.QCheckBox(self.widget5)
        self.CH5checkBox.setObjectName("CH5checkBox")
        self.gridLayout_4.addWidget(self.CH5checkBox, 1, 1, 1, 1)
        self.CH4checkBox = QtWidgets.QCheckBox(self.widget5)
        self.CH4checkBox.setObjectName("CH4checkBox")
        self.gridLayout_4.addWidget(self.CH4checkBox, 0, 1, 1, 1)
        self.CH6checkBox = QtWidgets.QCheckBox(self.widget5)
        self.CH6checkBox.setObjectName("CH6checkBox")
        self.gridLayout_4.addWidget(self.CH6checkBox, 3, 1, 1, 1)
        self.CH7checkBox = QtWidgets.QCheckBox(self.widget5)
        self.CH7checkBox.setObjectName("CH7checkBox")
        self.gridLayout_4.addWidget(self.CH7checkBox, 4, 1, 1, 1)
        self.CH2checkBox = QtWidgets.QCheckBox(self.widget5)
        self.CH2checkBox.setObjectName("CH2checkBox")
        self.gridLayout_4.addWidget(self.CH2checkBox, 3, 0, 1, 1)
        self.writeDataPushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.writeDataPushButton.setGeometry(QtCore.QRect(200, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.writeDataPushButton.setFont(font)
        self.writeDataPushButton.setObjectName("writeDataPushButton")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(590, 230, 311, 81))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.readDataComboBox = QtWidgets.QComboBox(self.groupBox_6)
        self.readDataComboBox.setGeometry(QtCore.QRect(50, 30, 69, 22))
        self.readDataComboBox.setObjectName("readDataComboBox")
        self.readDataComboBox.addItem("")
        self.readDataComboBox.addItem("")
        self.readDataComboBox.addItem("")
        self.readDataComboBox.addItem("")
        self.readDataComboBox.addItem("")
        self.readDataComboBox.addItem("")
        self.readDataComboBox.addItem("")
        self.readDataComboBox.addItem("")
        self.readDataPushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.readDataPushButton.setGeometry(QtCore.QRect(140, 30, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.readDataPushButton.setFont(font)
        self.readDataPushButton.setObjectName("readDataPushButton")
        self.clearAllPushButton = QtWidgets.QPushButton(self.tab_2)
        self.clearAllPushButton.setGeometry(QtCore.QRect(660, 350, 141, 31))
        self.clearAllPushButton.setObjectName("clearAllPushButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 421, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 271, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.manReadPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.manReadPushButton.setObjectName("manReadPushButton")
        self.gridLayout_3.addWidget(self.manReadPushButton, 2, 1, 1, 1)
        self.manValLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.manValLineEdit.setObjectName("manValLineEdit")
        self.gridLayout_3.addWidget(self.manValLineEdit, 1, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.manRegLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.manRegLineEdit.setObjectName("manRegLineEdit")
        self.gridLayout_3.addWidget(self.manRegLineEdit, 0, 1, 1, 3)
        self.manWritePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.manWritePushButton.setObjectName("manWritePushButton")
        self.gridLayout_3.addWidget(self.manWritePushButton, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 4, 1, 1)
        self.widget6 = QtWidgets.QWidget(self.groupBox_3)
        self.widget6.setGeometry(QtCore.QRect(290, 40, 122, 54))
        self.widget6.setObjectName("widget6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.manConnPushButton = QtWidgets.QPushButton(self.widget6)
        self.manConnPushButton.setObjectName("manConnPushButton")
        self.verticalLayout.addWidget(self.manConnPushButton)
        self.manResetPushButton = QtWidgets.QPushButton(self.widget6)
        self.manResetPushButton.setObjectName("manResetPushButton")
        self.verticalLayout.addWidget(self.manResetPushButton)
        self.toolBox_2 = QtWidgets.QToolBox(self.tab_3)
        self.toolBox_2.setGeometry(QtCore.QRect(470, 10, 491, 451))
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 491, 316))
        self.page_6.setObjectName("page_6")
        self.label_6 = QtWidgets.QLabel(self.page_6)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 101, 21))
        self.label_6.setObjectName("label_6")
        self.ADDR_lineEdit = QtWidgets.QLineEdit(self.page_6)
        self.ADDR_lineEdit.setGeometry(QtCore.QRect(110, 40, 113, 20))
        self.ADDR_lineEdit.setObjectName("ADDR_lineEdit")
        self.label_11 = QtWidgets.QLabel(self.page_6)
        self.label_11.setGeometry(QtCore.QRect(20, 80, 101, 21))
        self.label_11.setObjectName("label_11")
        self.READDONE_comboBox = QtWidgets.QComboBox(self.page_6)
        self.READDONE_comboBox.setGeometry(QtCore.QRect(130, 80, 69, 22))
        self.READDONE_comboBox.setObjectName("READDONE_comboBox")
        self.READDONE_comboBox.addItem("")
        self.READDONE_comboBox.addItem("")
        self.toolBox_2.addItem(self.page_6, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 491, 316))
        self.page_7.setObjectName("page_7")
        self.label_22 = QtWidgets.QLabel(self.page_7)
        self.label_22.setGeometry(QtCore.QRect(30, 20, 81, 16))
        self.label_22.setObjectName("label_22")
        self.PWDN7checkBox = QtWidgets.QCheckBox(self.page_7)
        self.PWDN7checkBox.setGeometry(QtCore.QRect(150, 20, 70, 17))
        self.PWDN7checkBox.setObjectName("PWDN7checkBox")
        self.PWDN6checkBox = QtWidgets.QCheckBox(self.page_7)
        self.PWDN6checkBox.setGeometry(QtCore.QRect(150, 40, 70, 17))
        self.PWDN6checkBox.setObjectName("PWDN6checkBox")
        self.PWDN5checkBox = QtWidgets.QCheckBox(self.page_7)
        self.PWDN5checkBox.setGeometry(QtCore.QRect(150, 60, 70, 17))
        self.PWDN5checkBox.setObjectName("PWDN5checkBox")
        self.PWDN4checkBox = QtWidgets.QCheckBox(self.page_7)
        self.PWDN4checkBox.setGeometry(QtCore.QRect(150, 80, 70, 17))
        self.PWDN4checkBox.setObjectName("PWDN4checkBox")
        self.PWDN3checkBox = QtWidgets.QCheckBox(self.page_7)
        self.PWDN3checkBox.setGeometry(QtCore.QRect(220, 20, 70, 17))
        self.PWDN3checkBox.setObjectName("PWDN3checkBox")
        self.PWDN2checkBox = QtWidgets.QCheckBox(self.page_7)
        self.PWDN2checkBox.setGeometry(QtCore.QRect(220, 40, 70, 17))
        self.PWDN2checkBox.setObjectName("PWDN2checkBox")
        self.PWDN1checkBox = QtWidgets.QCheckBox(self.page_7)
        self.PWDN1checkBox.setGeometry(QtCore.QRect(220, 60, 70, 17))
        self.PWDN1checkBox.setObjectName("PWDN1checkBox")
        self.PWDN0checkBox = QtWidgets.QCheckBox(self.page_7)
        self.PWDN0checkBox.setGeometry(QtCore.QRect(220, 80, 70, 16))
        self.PWDN0checkBox.setObjectName("PWDN0checkBox")
        self.toolBox_2.addItem(self.page_7, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_23 = QtWidgets.QLabel(self.page_8)
        self.label_23.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_23.setObjectName("label_23")
        self.OVERRXDET_comboBox = QtWidgets.QComboBox(self.page_8)
        self.OVERRXDET_comboBox.setGeometry(QtCore.QRect(110, 10, 69, 22))
        self.OVERRXDET_comboBox.setObjectName("OVERRXDET_comboBox")
        self.OVERRXDET_comboBox.addItem("")
        self.OVERRXDET_comboBox.addItem("")
        self.label_28 = QtWidgets.QLabel(self.page_8)
        self.label_28.setGeometry(QtCore.QRect(20, 60, 101, 16))
        self.label_28.setObjectName("label_28")
        self.RXDET_comboBox = QtWidgets.QComboBox(self.page_8)
        self.RXDET_comboBox.setGeometry(QtCore.QRect(100, 60, 221, 22))
        self.RXDET_comboBox.setObjectName("RXDET_comboBox")
        self.RXDET_comboBox.addItem("")
        self.RXDET_comboBox.addItem("")
        self.LPBK_comboBox = QtWidgets.QComboBox(self.page_8)
        self.LPBK_comboBox.setGeometry(QtCore.QRect(120, 100, 201, 22))
        self.LPBK_comboBox.setObjectName("LPBK_comboBox")
        self.LPBK_comboBox.addItem("")
        self.LPBK_comboBox.addItem("")
        self.LPBK_comboBox.addItem("")
        self.LPBK_comboBox.addItem("")
        self.label_29 = QtWidgets.QLabel(self.page_8)
        self.label_29.setGeometry(QtCore.QRect(20, 100, 101, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.page_8)
        self.label_30.setGeometry(QtCore.QRect(20, 150, 101, 16))
        self.label_30.setObjectName("label_30")
        self.OPRSNT_comboBox = QtWidgets.QComboBox(self.page_8)
        self.OPRSNT_comboBox.setGeometry(QtCore.QRect(150, 150, 181, 22))
        self.OPRSNT_comboBox.setObjectName("OPRSNT_comboBox")
        self.OPRSNT_comboBox.addItem("")
        self.OPRSNT_comboBox.addItem("")
        self.toolBox_2.addItem(self.page_8, "")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.label_31 = QtWidgets.QLabel(self.page_10)
        self.label_31.setGeometry(QtCore.QRect(30, 30, 101, 16))
        self.label_31.setObjectName("label_31")
        self.OSDTHcomboBox = QtWidgets.QComboBox(self.page_10)
        self.OSDTHcomboBox.setGeometry(QtCore.QRect(140, 30, 271, 22))
        self.OSDTHcomboBox.setObjectName("OSDTHcomboBox")
        self.OSDTHcomboBox.addItem("")
        self.OSDTHcomboBox.addItem("")
        self.OIDLEcomboBox = QtWidgets.QComboBox(self.page_10)
        self.OIDLEcomboBox.setGeometry(QtCore.QRect(130, 60, 281, 22))
        self.OIDLEcomboBox.setObjectName("OIDLEcomboBox")
        self.OIDLEcomboBox.addItem("")
        self.OIDLEcomboBox.addItem("")
        self.label_32 = QtWidgets.QLabel(self.page_10)
        self.label_32.setGeometry(QtCore.QRect(20, 60, 101, 20))
        self.label_32.setObjectName("label_32")
        self.ORXDETcomboBox = QtWidgets.QComboBox(self.page_10)
        self.ORXDETcomboBox.setGeometry(QtCore.QRect(130, 100, 281, 22))
        self.ORXDETcomboBox.setObjectName("ORXDETcomboBox")
        self.ORXDETcomboBox.addItem("")
        self.ORXDETcomboBox.addItem("")
        self.label_33 = QtWidgets.QLabel(self.page_10)
        self.label_33.setGeometry(QtCore.QRect(26, 100, 91, 20))
        self.label_33.setObjectName("label_33")
        self.ORATEcomboBox = QtWidgets.QComboBox(self.page_10)
        self.ORATEcomboBox.setGeometry(QtCore.QRect(120, 140, 251, 22))
        self.ORATEcomboBox.setObjectName("ORATEcomboBox")
        self.ORATEcomboBox.addItem("")
        self.ORATEcomboBox.addItem("")
        self.label_34 = QtWidgets.QLabel(self.page_10)
        self.label_34.setGeometry(QtCore.QRect(16, 140, 91, 20))
        self.label_34.setObjectName("label_34")
        self.toolBox_2.addItem(self.page_10, "")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.label_35 = QtWidgets.QLabel(self.page_11)
        self.label_35.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.label_35.setObjectName("label_35")
        self.SDTH0checkBox = QtWidgets.QCheckBox(self.page_11)
        self.SDTH0checkBox.setGeometry(QtCore.QRect(240, 90, 70, 16))
        self.SDTH0checkBox.setCheckable(False)
        self.SDTH0checkBox.setObjectName("SDTH0checkBox")
        self.SDTH1checkBox = QtWidgets.QCheckBox(self.page_11)
        self.SDTH1checkBox.setGeometry(QtCore.QRect(240, 70, 70, 17))
        self.SDTH1checkBox.setCheckable(False)
        self.SDTH1checkBox.setObjectName("SDTH1checkBox")
        self.SDTH6checkBox = QtWidgets.QCheckBox(self.page_11)
        self.SDTH6checkBox.setGeometry(QtCore.QRect(170, 50, 70, 17))
        self.SDTH6checkBox.setCheckable(False)
        self.SDTH6checkBox.setObjectName("SDTH6checkBox")
        self.SDTH4checkBox = QtWidgets.QCheckBox(self.page_11)
        self.SDTH4checkBox.setGeometry(QtCore.QRect(170, 90, 70, 17))
        self.SDTH4checkBox.setCheckable(False)
        self.SDTH4checkBox.setObjectName("SDTH4checkBox")
        self.SDTH3checkBox = QtWidgets.QCheckBox(self.page_11)
        self.SDTH3checkBox.setGeometry(QtCore.QRect(240, 30, 70, 17))
        self.SDTH3checkBox.setCheckable(False)
        self.SDTH3checkBox.setObjectName("SDTH3checkBox")
        self.SDTH7checkBox = QtWidgets.QCheckBox(self.page_11)
        self.SDTH7checkBox.setGeometry(QtCore.QRect(170, 30, 70, 17))
        self.SDTH7checkBox.setCheckable(False)
        self.SDTH7checkBox.setObjectName("SDTH7checkBox")
        self.SDTH5checkBox = QtWidgets.QCheckBox(self.page_11)
        self.SDTH5checkBox.setGeometry(QtCore.QRect(170, 70, 70, 17))
        self.SDTH5checkBox.setCheckable(False)
        self.SDTH5checkBox.setObjectName("SDTH5checkBox")
        self.SDTH2checkBox = QtWidgets.QCheckBox(self.page_11)
        self.SDTH2checkBox.setGeometry(QtCore.QRect(240, 50, 70, 17))
        self.SDTH2checkBox.setCheckable(False)
        self.SDTH2checkBox.setObjectName("SDTH2checkBox")
        self.toolBox_2.addItem(self.page_11, "")
        self.writeGenPushButton = QtWidgets.QPushButton(self.tab_3)
        self.writeGenPushButton.setGeometry(QtCore.QRect(130, 270, 75, 23))
        self.writeGenPushButton.setObjectName("writeGenPushButton")
        self.readGenPushButton = QtWidgets.QPushButton(self.tab_3)
        self.readGenPushButton.setGeometry(QtCore.QRect(200, 320, 75, 23))
        self.readGenPushButton.setObjectName("readGenPushButton")
        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 520, 411, 241))
        self.groupBox_4.setObjectName("groupBox_4")
        self.logTextEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.logTextEdit.setGeometry(QtCore.QRect(10, 20, 391, 161))
        self.logTextEdit.setObjectName("logTextEdit")
        self.clearLogPushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.clearLogPushButton.setGeometry(QtCore.QRect(170, 200, 75, 23))
        self.clearLogPushButton.setObjectName("clearLogPushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(530, 560, 291, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget7 = QtWidgets.QWidget(self.groupBox_2)
        self.widget7.setGeometry(QtCore.QRect(10, 20, 192, 71))
        self.widget7.setObjectName("widget7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget7)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget7)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.portComboBox = QtWidgets.QComboBox(self.widget7)
        self.portComboBox.setObjectName("portComboBox")
        self.gridLayout_2.addWidget(self.portComboBox, 0, 1, 1, 1)
        self.refrPortPushButton = QtWidgets.QPushButton(self.widget7)
        self.refrPortPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refrPortPushButton.setIcon(icon)
        self.refrPortPushButton.setObjectName("refrPortPushButton")
        self.gridLayout_2.addWidget(self.refrPortPushButton, 0, 2, 1, 1)
        self.openPortPushButton = QtWidgets.QPushButton(self.widget7)
        self.openPortPushButton.setObjectName("openPortPushButton")
        self.gridLayout_2.addWidget(self.openPortPushButton, 1, 0, 1, 1)
        self.closePortPushButton = QtWidgets.QPushButton(self.widget7)
        self.closePortPushButton.setObjectName("closePortPushButton")
        self.gridLayout_2.addWidget(self.closePortPushButton, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1229, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(4)
        self.toolBox_2.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Эквалайзеры"))
        self.label_10.setText(_translate("MainWindow", "RXDET"))
        self.label_9.setText(_translate("MainWindow", "IDLE_SEL"))
        self.label_8.setText(_translate("MainWindow", "IDLE_AUTO"))
        self.IDLE_SELcomboBox.setItemText(0, _translate("MainWindow", "Output is MUTED (electrical idle)"))
        self.IDLE_SELcomboBox.setItemText(1, _translate("MainWindow", "Output is ON"))
        self.IDLE_AUTOcomboBox.setItemText(0, _translate("MainWindow", "Allow IDLE_SEL control in bit 4"))
        self.IDLE_AUTOcomboBox.setItemText(1, _translate("MainWindow", "Automatic IDLE detect"))
        self.RXDETcomboBox.setItemText(0, _translate("MainWindow", "Input is hi-Z impedance"))
        self.RXDETcomboBox.setItemText(1, _translate("MainWindow", "Auto RX-Detect,\n"
"outputs test every 12 ms for 600 ms (50 times)\n"
"then stops; termination is hi-Z until detection;\n"
"once detected input termination is 50 Ω"))
        self.RXDETcomboBox.setItemText(2, _translate("MainWindow", "Auto RX-Detect,\n"
"outputs test every 12 ms until detection occurs;\n"
"termination is hi-Z until detection; once detected\n"
"input termination is 50 Ω"))
        self.RXDETcomboBox.setItemText(3, _translate("MainWindow", "Input is 50 Ω"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "IDLE, RXDET"))
        self.label_12.setText(_translate("MainWindow", "EQ Control"))
        self.label_14.setText(_translate("MainWindow", "dB at 2.5 GHz"))
        self.label_13.setText(_translate("MainWindow", "dB at 1.25 GHz"))
        self.EQControlcomboBox.setItemText(0, _translate("MainWindow", "2.1 | 3.7 | 4.9"))
        self.EQControlcomboBox.setItemText(1, _translate("MainWindow", "3.4 | 5.8 | 7.9"))
        self.EQControlcomboBox.setItemText(2, _translate("MainWindow", "4.8 | 7.7 | 9.9"))
        self.EQControlcomboBox.setItemText(3, _translate("MainWindow", "5.9 | 8.9 | 11.0"))
        self.EQControlcomboBox.setItemText(4, _translate("MainWindow", "7.2 | 11.2 | 14.3"))
        self.EQControlcomboBox.setItemText(5, _translate("MainWindow", "6.1 | 11.4 | 14.6"))
        self.EQControlcomboBox.setItemText(6, _translate("MainWindow", "8.8 |  13.5 | 17.0"))
        self.EQControlcomboBox.setItemText(7, _translate("MainWindow", "10.2 | 15.0 | 18.5"))
        self.EQControlcomboBox.setItemText(8, _translate("MainWindow", "7.5 |  12.8 | 18.0 "))
        self.EQControlcomboBox.setItemText(9, _translate("MainWindow", "11.4 | 17.4 | 22.0"))
        self.EQControlcomboBox.setItemText(10, _translate("MainWindow", "13.0 | 19.7 | 22.4"))
        self.EQControlcomboBox.setItemText(11, _translate("MainWindow", "14.2 | 21.1 | 25.8"))
        self.EQControlcomboBox.setItemText(12, _translate("MainWindow", "13.8 | 21.7 | 27.4"))
        self.EQControlcomboBox.setItemText(13, _translate("MainWindow", "15.6 | 23.5 | 29.0"))
        self.EQControlcomboBox.setItemText(14, _translate("MainWindow", "17.2 | 25.8 | 31.4"))
        self.EQControlcomboBox.setItemText(15, _translate("MainWindow", "18.4 | 27.3 | 32.7"))
        self.label_15.setText(_translate("MainWindow", "dB at 4 GHz"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "EQ"))
        self.label_16.setText(_translate("MainWindow", "Short Circuit  Protection"))
        self.SCPcomboBox.setItemText(0, _translate("MainWindow", "Enable the short circuit protection"))
        self.SCPcomboBox.setItemText(1, _translate("MainWindow", "Disable the short circuit protection"))
        self.label_17.setText(_translate("MainWindow", "RATE_SEL"))
        self.RATE_SELcomboBox.setItemText(0, _translate("MainWindow", "Gen 1/2"))
        self.RATE_SELcomboBox.setItemText(1, _translate("MainWindow", "Gen 3"))
        self.label_18.setText(_translate("MainWindow", "VOD Control"))
        self.VODCcomboBox.setItemText(0, _translate("MainWindow", "0.7 V"))
        self.VODCcomboBox.setItemText(1, _translate("MainWindow", "0.8 V"))
        self.VODCcomboBox.setItemText(2, _translate("MainWindow", "0.9 V"))
        self.VODCcomboBox.setItemText(3, _translate("MainWindow", "1.0 V"))
        self.VODCcomboBox.setItemText(4, _translate("MainWindow", "1.1 V"))
        self.VODCcomboBox.setItemText(5, _translate("MainWindow", "1.2 V"))
        self.VODCcomboBox.setItemText(6, _translate("MainWindow", "1.3 V"))
        self.VODCcomboBox.setItemText(7, _translate("MainWindow", "1.4 V"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "VOD"))
        self.label_21.setText(_translate("MainWindow", "DEM Control"))
        self.DEMcomboBox.setItemText(0, _translate("MainWindow", "0 dB"))
        self.DEMcomboBox.setItemText(1, _translate("MainWindow", "–1.5 dB"))
        self.DEMcomboBox.setItemText(2, _translate("MainWindow", "–3.5 dB"))
        self.DEMcomboBox.setItemText(3, _translate("MainWindow", "–5 dB"))
        self.DEMcomboBox.setItemText(4, _translate("MainWindow", "–6 dB"))
        self.DEMcomboBox.setItemText(5, _translate("MainWindow", "–8 dB"))
        self.DEMcomboBox.setItemText(6, _translate("MainWindow", "–9 dB"))
        self.DEMcomboBox.setItemText(7, _translate("MainWindow", "–12 dB"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "DEM"))
        self.label_19.setText(_translate("MainWindow", "IDLE tha"))
        self.IDLEthacomboBox.setItemText(0, _translate("MainWindow", "180 mVp-p"))
        self.IDLEthacomboBox.setItemText(1, _translate("MainWindow", "160 mVp-p"))
        self.IDLEthacomboBox.setItemText(2, _translate("MainWindow", "210 mVp-p"))
        self.IDLEthacomboBox.setItemText(3, _translate("MainWindow", "190 mVp-p"))
        self.label_20.setText(_translate("MainWindow", "IDLE thd"))
        self.IDLEthdcomboBox.setItemText(0, _translate("MainWindow", "110 mVp-p"))
        self.IDLEthdcomboBox.setItemText(1, _translate("MainWindow", "100 mVp-p"))
        self.IDLEthdcomboBox.setItemText(2, _translate("MainWindow", "150 mVp-p"))
        self.IDLEthdcomboBox.setItemText(3, _translate("MainWindow", "130 mVp-p"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "IDLE Threshold"))
        self.CH0checkBox.setText(_translate("MainWindow", "0"))
        self.CH1checkBox.setText(_translate("MainWindow", "1"))
        self.CH3checkBox.setText(_translate("MainWindow", "3"))
        self.CH5checkBox.setText(_translate("MainWindow", "5"))
        self.CH4checkBox.setText(_translate("MainWindow", "4"))
        self.CH6checkBox.setText(_translate("MainWindow", "6"))
        self.CH7checkBox.setText(_translate("MainWindow", "7"))
        self.CH2checkBox.setText(_translate("MainWindow", "2"))
        self.writeDataPushButton.setText(_translate("MainWindow", "Запись"))
        self.readDataComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.readDataComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.readDataComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.readDataComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.readDataComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.readDataComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.readDataComboBox.setItemText(6, _translate("MainWindow", "6"))
        self.readDataComboBox.setItemText(7, _translate("MainWindow", "7"))
        self.readDataPushButton.setText(_translate("MainWindow", "Чтение"))
        self.clearAllPushButton.setText(_translate("MainWindow", "Сброс всех регистров"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Каналы"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Ручной режим"))
        self.manReadPushButton.setText(_translate("MainWindow", "Считать"))
        self.manValLineEdit.setText(_translate("MainWindow", "0x0"))
        self.label_2.setText(_translate("MainWindow", "Регистр:"))
        self.manRegLineEdit.setText(_translate("MainWindow", "0x10"))
        self.manWritePushButton.setText(_translate("MainWindow", "Записать"))
        self.label_3.setText(_translate("MainWindow", "Значение"))
        self.label_4.setText(_translate("MainWindow", "(hex)"))
        self.label_5.setText(_translate("MainWindow", "(hex)"))
        self.manConnPushButton.setText(_translate("MainWindow", "Проверка соединения"))
        self.manResetPushButton.setText(_translate("MainWindow", "Сброс соединения"))
        self.label_6.setText(_translate("MainWindow", "Address Bit (RO)"))
        self.label_11.setText(_translate("MainWindow", "EEPROM Read Done"))
        self.READDONE_comboBox.setItemText(0, _translate("MainWindow", "Set"))
        self.READDONE_comboBox.setItemText(1, _translate("MainWindow", "Reset"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_6), _translate("MainWindow", "Device Address Observation"))
        self.label_22.setText(_translate("MainWindow", "PWDN CHx"))
        self.PWDN7checkBox.setText(_translate("MainWindow", "CH7"))
        self.PWDN6checkBox.setText(_translate("MainWindow", "CH6"))
        self.PWDN5checkBox.setText(_translate("MainWindow", "CH5"))
        self.PWDN4checkBox.setText(_translate("MainWindow", "CH4"))
        self.PWDN3checkBox.setText(_translate("MainWindow", "CH3"))
        self.PWDN2checkBox.setText(_translate("MainWindow", "CH2"))
        self.PWDN1checkBox.setText(_translate("MainWindow", "CH1"))
        self.PWDN0checkBox.setText(_translate("MainWindow", "CH0"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_7), _translate("MainWindow", "PWDN Channels"))
        self.label_23.setText(_translate("MainWindow", "Override RXDET"))
        self.OVERRXDET_comboBox.setItemText(0, _translate("MainWindow", "Set"))
        self.OVERRXDET_comboBox.setItemText(1, _translate("MainWindow", "Reset"))
        self.label_28.setText(_translate("MainWindow", "RXDET Value"))
        self.RXDET_comboBox.setItemText(0, _translate("MainWindow", "Set Rx Detect State Machine Reset"))
        self.RXDET_comboBox.setItemText(1, _translate("MainWindow", "Clear Rx Detect State Machine Reset"))
        self.LPBK_comboBox.setItemText(0, _translate("MainWindow", "Use LPBK pin control"))
        self.LPBK_comboBox.setItemText(1, _translate("MainWindow", "INA_n to OUTB_n loopback"))
        self.LPBK_comboBox.setItemText(2, _translate("MainWindow", "INB_n to OUTA_n loopback"))
        self.LPBK_comboBox.setItemText(3, _translate("MainWindow", "Disable loopback and ignore LPBK pin"))
        self.label_29.setText(_translate("MainWindow", "LPBK Control"))
        self.label_30.setText(_translate("MainWindow", "Override PRSNT pin"))
        self.OPRSNT_comboBox.setItemText(0, _translate("MainWindow", "Block PRSNT pin control"))
        self.OPRSNT_comboBox.setItemText(1, _translate("MainWindow", "Allow PRSNT pin control"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_8), _translate("MainWindow", "Override PRSNT, LPBK Control"))
        self.label_31.setText(_translate("MainWindow", "Override SD_TH"))
        self.OSDTHcomboBox.setItemText(0, _translate("MainWindow", "Block SD_TH pin control"))
        self.OSDTHcomboBox.setItemText(1, _translate("MainWindow", "Allow SD_TH pin control"))
        self.OIDLEcomboBox.setItemText(0, _translate("MainWindow", "IDLE control by registers"))
        self.OIDLEcomboBox.setItemText(1, _translate("MainWindow", "IDLE control by signal detect"))
        self.label_32.setText(_translate("MainWindow", "Override IDLE"))
        self.ORXDETcomboBox.setItemText(0, _translate("MainWindow", "Block RXDET pin control"))
        self.ORXDETcomboBox.setItemText(1, _translate("MainWindow", "Allow RXDET pin control"))
        self.label_33.setText(_translate("MainWindow", "Override RXDET"))
        self.ORATEcomboBox.setItemText(0, _translate("MainWindow", "Block RATE pin control"))
        self.ORATEcomboBox.setItemText(1, _translate("MainWindow", "Allow RATE pin control"))
        self.label_34.setText(_translate("MainWindow", "Override RATE"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_10), _translate("MainWindow", "Override Pin Control"))
        self.label_35.setText(_translate("MainWindow", "SD_TH Status(RO)"))
        self.SDTH0checkBox.setText(_translate("MainWindow", "CH0"))
        self.SDTH1checkBox.setText(_translate("MainWindow", "CH1"))
        self.SDTH6checkBox.setText(_translate("MainWindow", "CH6"))
        self.SDTH4checkBox.setText(_translate("MainWindow", "CH4"))
        self.SDTH3checkBox.setText(_translate("MainWindow", "CH3"))
        self.SDTH7checkBox.setText(_translate("MainWindow", "CH7"))
        self.SDTH5checkBox.setText(_translate("MainWindow", "CH5"))
        self.SDTH2checkBox.setText(_translate("MainWindow", "CH2"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_11), _translate("MainWindow", "Signal Detect Monitor"))
        self.writeGenPushButton.setText(_translate("MainWindow", "Запись"))
        self.readGenPushButton.setText(_translate("MainWindow", "Чтение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Общее"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Лог"))
        self.clearLogPushButton.setText(_translate("MainWindow", "Очистить"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Порт"))
        self.label.setText(_translate("MainWindow", "Порт:"))
        self.openPortPushButton.setText(_translate("MainWindow", "Открыть"))
        self.closePortPushButton.setText(_translate("MainWindow", "Закрыть"))


